name: Release
run-name: release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build
      - uses: softprops/action-gh-release@v2
        with:
          files: build/termfm